### ISSUE TITLE
LP 1 Lab 2 Ex 1 Task 5 Step 19 issue with selecting an account 

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/MS-4002-Prepare-security-and-compliance-to-support-Microsoft-365-Copilot#2]
LP 1
Lab 2 Exercise 1
Task 5
Step 19

Description of issue:
- This step will not work because an account for Laura has not been created previously in the lab. Adele's account was used instead in order to complete the task.

**Comment by tfrink** [comment]
I updated the steps to replace all references to Laura with Adele Vance.
